name: three
version: 0.2.4+1
description: >
  A port of the three.js JavaScript 3D engine to Dart.
authors:
- Robert Silverton (github.com/robsilv)
- Nelson Silva <nelson.silva@inevo.pt>
- Adam Singer <financeCoding@gmail.com>
- John <jwbito@gmail.com>
homepage: http://threedart.github.com/three.dart/
dependencies:
  browser: ">=0.3.2"